export enum ActionTypesEnum {
  SET_SEARCH_TERM = 'SET_SEARCH_TERM',
  FETCH_BOOKS_PENDING = 'FETCH_BOOKS_PENDING',
  FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS',
  FETCH_BOOKS_FAILED = 'FETCH_BOOKS_FAILED',
}
